// <auto-generated />
using System;
using FlowLedger.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlowLedger.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FlowLedgerDbContext))]
    [Migration("20260612041641_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlowLedger.Domain.Aggregates.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("account_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalAccountRef")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("external_account_ref");

                    b.Property<string>("Institution")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("institution");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastBalanceConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_balance_confirmed_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_accounts_tenant_id");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("FlowLedger.Domain.Aggregates.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("path");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_categories_tenant_id");

                    b.HasIndex("TenantId", "Path")
                        .HasDatabaseName("ix_categories_tenant_path");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("FlowLedger.Domain.Aggregates.RecurringFlow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("AmountModel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("amount_model");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Counterparty")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("counterparty");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("direction");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_recurring_flows_tenant_id");

                    b.HasIndex("TenantId", "AccountId")
                        .HasDatabaseName("ix_recurring_flows_tenant_account");

                    b.ToTable("recurring_flows", (string)null);
                });

            modelBuilder.Entity("FlowLedger.Domain.Aggregates.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("direction");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<Guid?>("MatchedOccurrenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("matched_occurrence_id");

                    b.Property<string>("MerchantName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("merchant_name");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<DateOnly?>("PostedDate")
                        .HasColumnType("date")
                        .HasColumnName("posted_date");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "EffectiveDate")
                        .HasDatabaseName("ix_transactions_tenant_date");

                    b.HasIndex("TenantId", "AccountId", "EffectiveDate")
                        .HasDatabaseName("ix_transactions_tenant_account_date");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("FlowLedger.Domain.Aggregates.Account", b =>
                {
                    b.OwnsOne("FlowLedger.Domain.ValueObjects.Money", "CreditLimit", b1 =>
                        {
                            b1.Property<Guid>("AccountId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("credit_limit_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("credit_limit_currency");

                            b1.HasKey("AccountId");

                            b1.ToTable("accounts");

                            b1.WithOwner()
                                .HasForeignKey("AccountId");
                        });

                    b.OwnsOne("FlowLedger.Domain.ValueObjects.Money", "CurrentBalance", b1 =>
                        {
                            b1.Property<Guid>("AccountId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("balance_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("balance_currency");

                            b1.HasKey("AccountId");

                            b1.ToTable("accounts");

                            b1.WithOwner()
                                .HasForeignKey("AccountId");
                        });

                    b.Navigation("CreditLimit");

                    b.Navigation("CurrentBalance")
                        .IsRequired();
                });

            modelBuilder.Entity("FlowLedger.Domain.Aggregates.RecurringFlow", b =>
                {
                    b.OwnsOne("FlowLedger.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("RecurringFlowId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.HasKey("RecurringFlowId");

                            b1.ToTable("recurring_flows");

                            b1.WithOwner()
                                .HasForeignKey("RecurringFlowId");
                        });

                    b.OwnsOne("FlowLedger.Domain.ValueObjects.DateOnlyRange", "ActiveWindow", b1 =>
                        {
                            b1.Property<Guid>("RecurringFlowId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly?>("End")
                                .HasColumnType("date")
                                .HasColumnName("active_end");

                            b1.Property<DateOnly>("Start")
                                .HasColumnType("date")
                                .HasColumnName("active_start");

                            b1.HasKey("RecurringFlowId");

                            b1.ToTable("recurring_flows");

                            b1.WithOwner()
                                .HasForeignKey("RecurringFlowId");
                        });

                    b.OwnsOne("FlowLedger.Domain.ValueObjects.RecurrencePattern", "Pattern", b1 =>
                        {
                            b1.Property<Guid>("RecurringFlowId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AnchorDayOfWeek")
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("recurrence_anchor_day_of_week");

                            b1.Property<int?>("DayOfMonth")
                                .HasColumnType("integer")
                                .HasColumnName("recurrence_day_of_month");

                            b1.Property<string>("Frequency")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("recurrence_frequency");

                            b1.Property<int?>("IntervalWeeks")
                                .HasColumnType("integer")
                                .HasColumnName("recurrence_interval_weeks");

                            b1.Property<int?>("SecondDayOfMonth")
                                .HasColumnType("integer")
                                .HasColumnName("recurrence_second_day_of_month");

                            b1.HasKey("RecurringFlowId");

                            b1.ToTable("recurring_flows");

                            b1.WithOwner()
                                .HasForeignKey("RecurringFlowId");
                        });

                    b.OwnsMany("FlowLedger.Domain.Aggregates.PlannedFlowOccurrence", "Occurrences", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int?>("DateVarianceDays")
                                .HasColumnType("integer")
                                .HasColumnName("date_variance_days");

                            b1.Property<string>("Direction")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("direction");

                            b1.Property<DateOnly>("PlannedDate")
                                .HasColumnType("date")
                                .HasColumnName("planned_date");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("status");

                            b1.Property<Guid>("_accountId")
                                .HasColumnType("uuid")
                                .HasColumnName("account_id");

                            b1.Property<decimal?>("_matchConfidence")
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("match_confidence");

                            b1.Property<Guid?>("_matchedTransactionId")
                                .HasColumnType("uuid")
                                .HasColumnName("matched_transaction_id");

                            b1.Property<Guid>("_tenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("tenant_id");

                            b1.Property<Guid>("recurring_flow_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("PlannedDate")
                                .HasDatabaseName("ix_planned_occurrences_date");

                            b1.HasIndex("recurring_flow_id");

                            b1.ToTable("planned_flow_occurrences", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("recurring_flow_id");

                            b1.OwnsOne("FlowLedger.Domain.ValueObjects.Money", "AmountVariance", b2 =>
                                {
                                    b2.Property<Guid>("PlannedFlowOccurrenceId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("amount_variance");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("amount_variance_currency");

                                    b2.HasKey("PlannedFlowOccurrenceId");

                                    b2.ToTable("planned_flow_occurrences");

                                    b2.WithOwner()
                                        .HasForeignKey("PlannedFlowOccurrenceId");
                                });

                            b1.OwnsOne("FlowLedger.Domain.ValueObjects.Money", "PlannedAmount", b2 =>
                                {
                                    b2.Property<Guid>("PlannedFlowOccurrenceId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("planned_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("planned_currency");

                                    b2.HasKey("PlannedFlowOccurrenceId");

                                    b2.ToTable("planned_flow_occurrences");

                                    b2.WithOwner()
                                        .HasForeignKey("PlannedFlowOccurrenceId");
                                });

                            b1.Navigation("AmountVariance");

                            b1.Navigation("PlannedAmount")
                                .IsRequired();
                        });

                    b.Navigation("ActiveWindow")
                        .IsRequired();

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Occurrences");

                    b.Navigation("Pattern")
                        .IsRequired();
                });

            modelBuilder.Entity("FlowLedger.Domain.Aggregates.Transaction", b =>
                {
                    b.OwnsOne("FlowLedger.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.HasKey("TransactionId");

                            b1.ToTable("transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.OwnsOne("FlowLedger.Domain.ValueObjects.TransactionFingerprint", "Fingerprint", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("fingerprint");

                            b1.HasKey("TransactionId");

                            b1.ToTable("transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.OwnsMany("FlowLedger.Domain.Aggregates.TransactionSplit", "Splits", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid?>("CategoryId")
                                .HasColumnType("uuid")
                                .HasColumnName("category_id");

                            b1.Property<string>("Notes")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("notes");

                            b1.Property<Guid>("transaction_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("transaction_id");

                            b1.ToTable("transaction_splits", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("transaction_id");

                            b1.OwnsOne("FlowLedger.Domain.ValueObjects.Money", "Amount", b2 =>
                                {
                                    b2.Property<int>("TransactionSplitId")
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("currency");

                                    b2.HasKey("TransactionSplitId");

                                    b2.ToTable("transaction_splits");

                                    b2.WithOwner()
                                        .HasForeignKey("TransactionSplitId");
                                });

                            b1.Navigation("Amount")
                                .IsRequired();
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Fingerprint");

                    b.Navigation("Splits");
                });
#pragma warning restore 612, 618
        }
    }
}
